---
namespaces: ['argocd', 'infra', 'monitoring', 'ingress-nginx']

applications:
  - name: argocd
    namespace: argocd
    chart: argo-cd
    targetRevision: 3.33.6
    repoURL: https://argoproj.github.io/argo-helm
  - name: cert-manager
    namespace: infra
    chart: cert-manager
    targetRevision: v1.8.0
    repoURL: https://charts.jetstack.io
  - name: tomcat
    namespace: infra
    chart: tomcat
    targetRevision: 10.3.9
    repoURL: https://charts.bitnami.com/bitnami
