{{- range $application := .Values.applications }}
{{- range $namespace := $application.namespaces }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $application.name }}-{{ $namespace }}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ $namespace }}
    server: https://kubernetes.default.svc
  project: default
  source:
    path: common
    repoURL: https://github.com/dmitrii-dmnk/argocd-working-example.git
    targetRevision: master
    helm:
      valueFiles:
        - values.yaml
        - values/{{ $application.name }}.yaml
        - values/{{ $namespace }}/{{ $application.name }}.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
{{- end }}
{{- end }}
